spring:
  datasource:
    url: jdbc:mysql://localhost:3306/CRUD_Example
    username: sfg_dev_user
    password: 12345  #use environment var.
  jpa:
    hibernate:
      ddl-auto: validate         #hibernate default : create-drop(drop when close)
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true

#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: database_create.sql